name: generateApiType
on: pull_request
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependecies
        run: bun install

      - name: Generate Api Type
        run: bun run api:build

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: generate api type
