name: generateApiType
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependecies
        run: bun install

      - name: Generate Api Type
        run: bun run api:build

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date + '%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Generate API Type"
